# Generated by Django 3.0.5 on 2020-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200405_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='corporaterequest',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
